In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import molmodmt as m3t
import numpy as np
import seaborn as sns
import nglview as nv
from simtk.unit import angstroms, nanometers
from scipy.spatial.qhull import Voronoi

/home/diego/Myopt/miniconda3/envs/UIBCDF_lab_dev/lib/python3.7/site-packages/yank/experiment.py:1170: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """)


_ColormakerRegistry()

# Alpha sphere

In [4]:
n_atoms = 5

In [5]:
coordinates = np.zeros([n_atoms,3],dtype='float64')*angstroms

In [6]:
m3t.get_form(coordinates)

'XYZ'

In [29]:
coordinates[0,:] = [1,3,5]*angstroms
coordinates[1,:] = [0,-2,1]*angstroms
coordinates[2,:] = [-1,3,-2]*angstroms
coordinates[3,:] = [2,3,-1]*angstroms
coordinates[4,:] = [-3,-1,4]*angstroms

In [30]:
coordinates.shape

(5, 3)

In [31]:
view = nv.NGLWidget()

for atom_index in range(n_atoms):
    atom_coordinates = coordinates[atom_index,:]._value
    view.shape.add_sphere(list(atom_coordinates), [0.8,0.0,0.0], 0.2)

view

NGLWidget()

In [35]:
result = Voronoi(coordinates, incremental=False)

In [36]:
print(result.vertices)

[[-1.09701493  1.76865672  1.81343284]
 [-0.55263158  1.78421053  1.65789474]]


In [40]:
result.min_bound

array([-3., -2., -2.])

In [34]:
help(result)

Help on Voronoi in module scipy.spatial.qhull object:

class Voronoi(_QhullUser)
 |  Voronoi(points, furthest_site=False, incremental=False, qhull_options=None)
 |  
 |  Voronoi(points, furthest_site=False, incremental=False, qhull_options=None)
 |  
 |  Voronoi diagrams in N dimensions.
 |  
 |  .. versionadded:: 0.12.0
 |  
 |  Parameters
 |  ----------
 |  points : ndarray of floats, shape (npoints, ndim)
 |      Coordinates of points to construct a convex hull from
 |  furthest_site : bool, optional
 |      Whether to compute a furthest-site Voronoi diagram. Default: False
 |  incremental : bool, optional
 |      Allow adding new points incrementally. This takes up some additional
 |      resources.
 |  qhull_options : str, optional
 |      Additional options to pass to Qhull. See Qhull manual
 |      for details. (Default: "Qbb Qc Qz Qx" for ndim > 4 and
 |      "Qbb Qc Qz" otherwise. Incremental mode omits "Qz".)
 |  
 |  Attributes
 |  ----------
 |  points : ndarray of double, 

In [11]:
distances = m3t.distance(item_1=coordinates, item_2=result.vertices*angstroms)

In [12]:
print(distances)

[[[ 7.18667342 11.92598774 18.73105443]
  [ 3.45556909 11.92598774 18.73105443]
  [ 3.45556909 11.92598774 20.39540144]
  [ 3.45556909 11.92598774 18.73105443]
  [ 3.45556909 13.73839399 18.73105443]]] A


In [13]:
result.vertices

array([[-0.08536585,  0.30487805, -1.57317073],
       [-9.72857143,  4.84285714,  0.12857143],
       [18.18      , -4.46      ,  4.78      ]])

In [ ]:
r_sphere = distances[0,0,0]._value

In [ ]:
view.shape.add_sphere(list(result.vertices[0]), [0.8,0.8,0.8], r_sphere)

## protein

In [ ]:
molsys = m3t.load('1sux.pdb')

In [ ]:
min_apol_neigh = 3 # Todavia no se lo que es

In [ ]:
selection_heavy_atoms = m3t.select(molsys, 'protein and not type H')

In [ ]:
coordinates = m3t.get(molsys, target='atom', selection=selection_heavy_atoms, coordinates=True)

In [ ]:
result = Voronoi(coordinates[0,:,:])

In [ ]:
voronoi_vertices = result.vertices*nanometers

In [ ]:
pairs, distances = m3t.minimum_distance(item_1=molsys, selection_1=selection_heavy_atoms,
                                        item_2=voronoi_vertices, selection_2='all',
                                        as_entity_1=True, as_entity_2=False)

In [ ]:
sns.kdeplot(distances[0], shade=True);

In [ ]:
threshold= 0.2 * nanometers

In [ ]:
np.sum(distances[0][:]<threshold)

In [ ]:
distances[0]

In [ ]:
len(distances[0][:])

In [ ]:
view = m3t.view(molsys)
view.clear()
view.add_ball_and_stick(selection_heavy_atoms)

#for vertex_index in range(voro.vertices.shape[0]):
for vertex_index in range(100):
    vertex_coordinates = voro.vertices[vertex_index,:]
    view.shape.add_sphere(list(vertex_coordinates), [0,1,0], 0.5)

#view.shape.add_sphere([0,0,0], [1,0,0], 2)
view



In [ ]:
m3t.minimum_distance()

### Sources, cites and additional information

https://plot.ly/python/alpha-shapes/
http://www.nyu.edu/projects/yzhang/AlphaSpace/index.html
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Voronoi.html
https://stackoverflow.com/questions/10650645/python-calculate-voronoi-tesselation-from-scipys-delaunay-triangulation-in-3d
http://www.qhull.org/
https://docs.scipy.org/doc/scipy-0.18.1/reference/spatial.html
https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.spatial.ConvexHull.html

